import type { User } from '@/types/auth';
import type {
  BuyerDemand,
  BuyerProfile,
  BuyerRecommendation,
  MarketplaceListing,
} from '@/types/buyer';
import type { Offer } from '@/types/offer';
import type { Transaction } from '@/types/transaction';
import type { Notification } from '@/types/notification';
import { DEMO_FARMER_ID, DEMO_LISTING_ID, demoListings } from './demo-data';

const now = new Date().toISOString();
const weekAgo = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString();
const twoDaysAgo = new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString();
const tomorrow = new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString();
const nextWeek = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString();
const nextMonday = new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString();

export const DEMO_BUYER_USER_ID = 'user-golden-spoon';
export const DEMO_BUYER_ID = 'buyer-golden-spoon';
export const DEMO_BUYER_DEMAND_ID = 'demand-tomatoes-weekly';
export const DEMO_BUYER_OFFER_ID = 'buyer-offer-001';
export const DEMO_BUYER_TRANSACTION_ID = 'buyer-txn-001';
export const DEMO_AGOGO_LISTING_ID = 'listing-tomatoes-agogo';

export const demoBuyerUser: User = {
  id: DEMO_BUYER_USER_ID,
  email: 'orders@goldenspoon.gh',
  phone: '+233244556677',
  fullName: 'Ama Darko',
  role: 'buyer',
  roles: ['buyer'],
  createdAt: weekAgo,
  updatedAt: now,
};

export const demoBuyerProfile: BuyerProfile = {
  id: DEMO_BUYER_ID,
  userId: DEMO_BUYER_USER_ID,
  businessName: 'Golden Spoon Restaurant',
  buyerType: 'restaurant',
  description:
    'Contemporary Ghanaian restaurant in Kumasi serving lunch and dinner with a focus on fresh local produce.',
  contactEmail: 'orders@goldenspoon.gh',
  contactPhone: '+233244556677',
  region: 'Ashanti',
  district: 'Kumasi Metropolitan',
  town: 'Kumasi',
  gpsCoordinates: { lat: 6.6885, lng: -1.6244 },
  maxTravelDistanceKm: 80,
  preferredProduce: ['Tomatoes', 'Plantain', 'Pepper', 'Cabbage'],
  commonUnits: ['crate', 'kg', 'basket'],
  typicalQuantityMin: 20,
  typicalQuantityMax: 100,
  purchaseFrequency: 'weekly',
  onboardingComplete: true,
  verificationStatus: 'verified',
  createdAt: weekAgo,
  updatedAt: now,
};

export const demoBuyerDemands: BuyerDemand[] = [
  {
    id: DEMO_BUYER_DEMAND_ID,
    buyerId: DEMO_BUYER_ID,
    produceCategory: 'Tomatoes',
    produceCategoryId: 'cat-tomatoes',
    quantityMin: 40,
    quantityMax: 80,
    unit: 'crate',
    preferredMaxPrice: 90,
    currency: 'GHS',
    requiredFrom: twoDaysAgo,
    requiredUntil: nextWeek,
    preferredRegions: ['Ashanti', 'Eastern'],
    isRecurring: true,
    frequency: 'weekly',
    status: 'partially_matched',
    matchingListingsCount: 3,
    createdAt: weekAgo,
    updatedAt: now,
  },
  {
    id: 'demand-plantain-weekly',
    buyerId: DEMO_BUYER_ID,
    produceCategory: 'Plantain',
    produceCategoryId: 'cat-fruits',
    quantityMin: 100,
    quantityMax: 200,
    unit: 'piece',
    preferredMaxPrice: 10,
    currency: 'GHS',
    requiredFrom: weekAgo,
    requiredUntil: nextWeek,
    preferredRegions: ['Ashanti'],
    isRecurring: true,
    frequency: 'weekly',
    status: 'matched',
    matchingListingsCount: 2,
    createdAt: weekAgo,
    updatedAt: now,
  },
  {
    id: 'demand-cabbage-seasonal',
    buyerId: DEMO_BUYER_ID,
    produceCategory: 'Cabbage',
    produceCategoryId: 'cat-vegetables',
    quantityMin: 30,
    quantityMax: 50,
    unit: 'crate',
    preferredMaxPrice: 75,
    currency: 'GHS',
    requiredFrom: nextWeek,
    requiredUntil: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    preferredRegions: ['Ashanti', 'Bono East'],
    isRecurring: false,
    status: 'unmatched',
    matchingListingsCount: 0,
    createdAt: twoDaysAgo,
    updatedAt: now,
  },
];

export const demoAgogoListing: MarketplaceListing = {
  id: DEMO_AGOGO_LISTING_ID,
  farmerId: 'farmer-agogo-tomatoes',
  farmerName: 'Kofi Asante',
  farmName: 'Agogo Valley Produce',
  farmerVerified: true,
  title: '60 Crates Roma Tomatoes — Agogo',
  categoryId: 'cat-tomatoes',
  categoryName: 'Tomatoes',
  produceType: 'Roma Tomatoes',
  quantity: 60,
  availableQuantity: 60,
  minimumOrder: 10,
  unit: 'crate',
  pricePerUnit: 82,
  currency: 'GHS',
  description:
    'Fresh Roma tomatoes ready next Monday at Agogo. Ideal for restaurants and market traders. Harvested at peak ripeness.',
  harvestDate: nextMonday,
  availableFrom: nextMonday,
  availableUntil: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
  region: 'Ashanti',
  district: 'Asante Akim North',
  town: 'Agogo',
  distanceKm: 32,
  matchScore: 94,
  qualityGrade: 'Grade A',
  farmingMethod: 'Conventional',
  status: 'active',
  aiConfidence: 'high',
  createdAt: twoDaysAgo,
  updatedAt: now,
};

export const demoMarketplaceListings: MarketplaceListing[] = [
  demoAgogoListing,
  {
    id: DEMO_LISTING_ID,
    farmerId: DEMO_FARMER_ID,
    farmerName: 'Kwame Mensah',
    farmName: 'Mensah Valley Farms',
    farmerVerified: true,
    title: 'Fresh Roma Tomatoes — Ejisu Farm',
    categoryId: 'cat-tomatoes',
    categoryName: 'Tomatoes',
    produceType: 'Roma Tomatoes',
    quantity: 150,
    availableQuantity: 150,
    minimumOrder: 20,
    unit: 'crate',
    pricePerUnit: 85,
    currency: 'GHS',
    description: 'Vine-ripened Roma tomatoes harvested this week.',
    harvestDate: twoDaysAgo,
    availableFrom: twoDaysAgo,
    availableUntil: nextWeek,
    region: 'Ashanti',
    district: 'Ejisu Municipal',
    town: 'Bonwire',
    distanceKm: 18,
    matchScore: 88,
    qualityGrade: 'Grade A',
    farmingMethod: 'Organic',
    status: 'active',
    aiConfidence: 'high',
    createdAt: twoDaysAgo,
    updatedAt: now,
  },
  {
    id: 'listing-plantain-kumasi',
    farmerId: DEMO_FARMER_ID,
    farmerName: 'Kwame Mensah',
    farmName: 'Mensah Valley Farms',
    farmerVerified: true,
    title: 'Apem Plantain Bunches',
    categoryId: 'cat-fruits',
    categoryName: 'Fruits',
    produceType: 'Apem Plantain',
    quantity: 200,
    availableQuantity: 200,
    minimumOrder: 50,
    unit: 'piece',
    pricePerUnit: 8,
    currency: 'GHS',
    region: 'Ashanti',
    district: 'Ejisu Municipal',
    town: 'Bonwire',
    distanceKm: 18,
    matchScore: 91,
    availableFrom: weekAgo,
    availableUntil: nextWeek,
    status: 'active',
    createdAt: weekAgo,
    updatedAt: now,
  },
  {
    id: 'listing-maize-techiman',
    farmerId: 'farmer-techiman-grains',
    farmerName: 'Yaw Boateng',
    farmName: 'Techiman Grain Collective',
    farmerVerified: true,
    title: 'Dried Maize — 200 Bags',
    categoryId: 'cat-grains',
    categoryName: 'Grains & Cereals',
    produceType: 'Maize',
    quantity: 200,
    availableQuantity: 200,
    minimumOrder: 10,
    unit: 'bag',
    pricePerUnit: 320,
    currency: 'GHS',
    region: 'Bono East',
    district: 'Techiman Municipal',
    town: 'Techiman',
    distanceKm: 95,
    availableFrom: weekAgo,
    availableUntil: nextWeek,
    status: 'active',
    createdAt: weekAgo,
    updatedAt: now,
  },
  {
    id: 'listing-pepper-kasoa',
    farmerId: 'farmer-kasoa-pepper',
    farmerName: 'Esi Adom',
    farmName: 'Kasoa Pepper Farms',
    farmerVerified: false,
    title: 'Green Pepper — 40 Crates',
    categoryId: 'cat-vegetables',
    categoryName: 'Vegetables',
    produceType: 'Green Pepper',
    quantity: 40,
    availableQuantity: 40,
    minimumOrder: 5,
    unit: 'crate',
    pricePerUnit: 95,
    currency: 'GHS',
    region: 'Central',
    district: 'Awutu Senya East',
    town: 'Kasoa',
    distanceKm: 210,
    availableFrom: twoDaysAgo,
    availableUntil: nextWeek,
    status: 'active',
    createdAt: twoDaysAgo,
    updatedAt: now,
  },
];

const agogoScoreBreakdown = {
  produce: 98,
  quantity: 95,
  distance: 88,
  date: 96,
  price: 92,
  total: 94,
};

export const demoBuyerRecommendations: BuyerRecommendation[] = [
  {
    id: 'rec-agogo-tomatoes',
    demandId: DEMO_BUYER_DEMAND_ID,
    listingId: DEMO_AGOGO_LISTING_ID,
    listingTitle: demoAgogoListing.title,
    produceType: 'Roma Tomatoes',
    farmerId: demoAgogoListing.farmerId,
    farmerName: demoAgogoListing.farmerName,
    farmName: demoAgogoListing.farmName,
    farmerVerified: true,
    quantity: 60,
    unit: 'crate',
    pricePerUnit: 82,
    currency: 'GHS',
    region: 'Ashanti',
    district: 'Asante Akim North',
    town: 'Agogo',
    distanceKm: 32,
    harvestDate: nextMonday,
    availableFrom: nextMonday,
    availableUntil: demoAgogoListing.availableUntil,
    score: 94,
    scoreLabel: 'Excellent alignment',
    scoreBreakdown: agogoScoreBreakdown,
    explanation:
      'This listing matches your tomato demand, provides enough quantity within your 40–80 crate range, is within your preferred travel distance and is available during your requested period. The price is below your preferred maximum.',
    status: 'new',
    createdAt: twoDaysAgo,
  },
  {
    id: 'rec-ejisu-tomatoes',
    demandId: DEMO_BUYER_DEMAND_ID,
    listingId: DEMO_LISTING_ID,
    listingTitle: 'Fresh Roma Tomatoes — Ejisu Farm',
    produceType: 'Roma Tomatoes',
    farmerId: DEMO_FARMER_ID,
    farmerName: 'Kwame Mensah',
    farmName: 'Mensah Valley Farms',
    farmerVerified: true,
    quantity: 150,
    unit: 'crate',
    pricePerUnit: 85,
    currency: 'GHS',
    region: 'Ashanti',
    district: 'Ejisu Municipal',
    town: 'Bonwire',
    distanceKm: 18,
    harvestDate: twoDaysAgo,
    availableFrom: twoDaysAgo,
    availableUntil: nextWeek,
    score: 88,
    scoreLabel: 'Strong alignment',
    scoreBreakdown: {
      produce: 98,
      quantity: 100,
      distance: 95,
      date: 85,
      price: 78,
      total: 88,
    },
    explanation:
      'Strong match for your weekly tomato demand with ample quantity available now. Closer than Agogo listing but slightly above your preferred maximum price.',
    status: 'viewed',
    createdAt: weekAgo,
  },
  {
    id: 'rec-plantain-ejisu',
    demandId: 'demand-plantain-weekly',
    listingId: 'listing-plantain-kumasi',
    listingTitle: 'Apem Plantain Bunches',
    produceType: 'Apem Plantain',
    farmerId: DEMO_FARMER_ID,
    farmerName: 'Kwame Mensah',
    farmName: 'Mensah Valley Farms',
    farmerVerified: true,
    quantity: 200,
    unit: 'piece',
    pricePerUnit: 8,
    currency: 'GHS',
    region: 'Ashanti',
    district: 'Ejisu Municipal',
    town: 'Bonwire',
    distanceKm: 18,
    availableFrom: weekAgo,
    availableUntil: nextWeek,
    score: 91,
    scoreLabel: 'Excellent alignment',
    scoreBreakdown: {
      produce: 100,
      quantity: 95,
      distance: 95,
      date: 90,
      price: 85,
      total: 91,
    },
    explanation:
      'Matches your recurring plantain demand with sufficient quantity and competitive pricing from a verified farmer nearby.',
    status: 'offer_sent',
    createdAt: weekAgo,
  },
];

export const demoBuyerOffers: Offer[] = [
  {
    id: DEMO_BUYER_OFFER_ID,
    listingId: DEMO_AGOGO_LISTING_ID,
    buyerId: DEMO_BUYER_ID,
    buyerName: 'Golden Spoon Restaurant',
    quantity: 50,
    unit: 'crate',
    pricePerUnit: 80,
    totalAmount: 4000,
    currency: 'GHS',
    message: 'Can arrange pickup from Agogo on Tuesday morning.',
    status: 'pending',
    expiresAt: nextWeek,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'buyer-offer-002',
    listingId: 'listing-plantain-kumasi',
    buyerId: DEMO_BUYER_ID,
    buyerName: 'Golden Spoon Restaurant',
    quantity: 150,
    unit: 'piece',
    pricePerUnit: 7.5,
    totalAmount: 1125,
    currency: 'GHS',
    message: 'Weekly supply for restaurant kitchen.',
    status: 'accepted',
    createdAt: weekAgo,
    updatedAt: twoDaysAgo,
  },
  {
    id: 'buyer-offer-003',
    listingId: DEMO_LISTING_ID,
    buyerId: DEMO_BUYER_ID,
    buyerName: 'Golden Spoon Restaurant',
    quantity: 60,
    unit: 'crate',
    pricePerUnit: 78,
    totalAmount: 4680,
    currency: 'GHS',
    status: 'rejected',
    createdAt: weekAgo,
    updatedAt: weekAgo,
  },
];

export const demoBuyerTransactions: Transaction[] = [
  {
    id: DEMO_BUYER_TRANSACTION_ID,
    offerId: 'buyer-offer-002',
    listingId: 'listing-plantain-kumasi',
    buyerId: DEMO_BUYER_ID,
    buyerName: 'Golden Spoon Restaurant',
    farmerId: DEMO_FARMER_ID,
    farmerName: 'Kwame Mensah',
    listingTitle: 'Apem Plantain Bunches',
    produceType: 'Apem Plantain',
    quantity: 150,
    unit: 'piece',
    pricePerUnit: 7.5,
    totalAmount: 1125,
    currency: 'GHS',
    status: 'payment_confirmed',
    deliveryDate: tomorrow,
    pickupLocation: 'Bonwire, Ejisu Municipal, Ashanti',
    region: 'Ashanti',
    createdAt: twoDaysAgo,
    updatedAt: now,
  },
];

export const demoBuyerNotifications: Notification[] = [
  {
    id: 'buyer-notif-001',
    userId: DEMO_BUYER_USER_ID,
    type: 'recommendation',
    title: 'New tomato supply matches your demand',
    body: '60 crates of Roma tomatoes available from Agogo — 94% match score.',
    read: false,
    actionUrl: '/buyer/recommendations/rec-agogo-tomatoes',
    createdAt: twoDaysAgo,
  },
  {
    id: 'buyer-notif-002',
    userId: DEMO_BUYER_USER_ID,
    type: 'offer',
    title: 'Offer sent to Kofi Asante',
    body: 'Your offer for 50 crates at GH₵80/crate is awaiting farmer response.',
    read: false,
    actionUrl: `/buyer/offers/${DEMO_BUYER_OFFER_ID}`,
    createdAt: now,
  },
  {
    id: 'buyer-notif-003',
    userId: DEMO_BUYER_USER_ID,
    type: 'transaction',
    title: 'Farmer accepted your plantain offer',
    body: 'Pickup scheduled for tomorrow at Bonwire, Ejisu Municipal.',
    read: true,
    actionUrl: `/buyer/transactions/${DEMO_BUYER_TRANSACTION_ID}`,
    createdAt: twoDaysAgo,
  },
  {
    id: 'buyer-notif-004',
    userId: DEMO_BUYER_USER_ID,
    type: 'pickup',
    title: 'Pickup approaching',
    body: 'Plantain pickup from Mensah Valley Farms is scheduled for tomorrow.',
    read: false,
    actionUrl: '/buyer/pickups',
    createdAt: now,
  },
];

export function listingToMarketplace(
  listing: (typeof demoListings)[0],
  extras?: Partial<MarketplaceListing>,
): MarketplaceListing {
  return {
    id: listing.id,
    farmerId: listing.farmerId,
    farmerName: 'Kwame Mensah',
    farmName: 'Mensah Valley Farms',
    farmerVerified: true,
    title: listing.title,
    categoryId: listing.categoryId,
    categoryName: listing.categoryName,
    produceType: listing.produceType,
    quantity: listing.quantity,
    availableQuantity: listing.quantity,
    minimumOrder: 10,
    unit: listing.unit,
    pricePerUnit: listing.pricePerUnit,
    currency: listing.currency,
    description: listing.description,
    harvestDate: listing.harvestDate,
    availableFrom: listing.availableFrom,
    availableUntil: listing.availableUntil,
    region: listing.region,
    district: listing.district,
    town: 'Bonwire',
    status: listing.status,
    aiConfidence: listing.aiConfidence,
    createdAt: listing.createdAt,
    updatedAt: listing.updatedAt,
    ...extras,
  };
}
